#服务器配置
server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8
#数据库配置
spring:
    datasource:
        druid:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://127.0.0.1:3306/mini?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
            username: root
            password: 123456
            filters: stat,wall
            stat-view-servlet:
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
    http:
        multipart:
            max-file-size: 1024MB
            max-request-size: 1024MB